spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezone
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        ejb:
          interceptor: com.kamdev.gestionstock.interceptor.Interceptor

    hibernate:
      ddl-auto: update
      dialect: "org.hibernate.dialect.MySQL5Dialect"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8083

flickr:
  apiKey: 86563349541e76e6e5d8dfcc9a5a1e07
  apiSecret: 33e3e51229728a96
  appKey: 72157720844389491-6482291377e7d0fd
  appSecret: 6391d1511c8fae95

